### ISSUE TITLE
Look into Pure "Other" Problem

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#115]
Pure has articles that are listed as a publication type of "other" and they appear to be "articles." Currently we are only importing the "article" type, but we need to investigate why these articles are marked "other" and how we can get these when/where appropriate.

**Comment by ajkiessl** [comment]
Some modifications to this:

Pure has many different publication types (i.e. Conference Proceeding, Article, Book, Chapter, etc.).  These are all classified as "Publications".  It seems like in researcher vernacular all of these are considered "Publications".  When researchers are looking at their profiles they are wondering why they are not seeing all of their publications (because we are not importing these other publications).

The solution is to import all of these other publications and classify their publication types as Article, Conference Proceeding, Book, or whatever.  For any exports (Activity Insight/ORCID) the exporters will need to make sure they aren't only exporting these publications as "Journal Article".

**Comment by ajkiessl** [comment]
If updating a record when importing from AI, don't update publication_type.  Only add publication_type from AI if creating new record.  This will help prevent constant flip-flopping of pub types.

**Comment by ajkiessl** [comment]
Some tasks:

- Return to JSON format for user profile 'other_publications'
- Change the code for the example site (deploy by going on the server and pulling from GitHub)
- Make new copy of downloadable source code and stick that in RMD
- Follow the etd pattern for the user profile json output
- Make sure you are filtering out all non-journals in the OA controllers

**Comment by ajkiessl** [comment]
> If updating a record when importing from AI, don't update publication_type. Only add publication_type from AI if creating new record. This will help prevent constant flip-flopping of pub types.

It might be better to totally skip any record that has an RMD ID.  Since the original record will likely be coming from Pure, we don't want cyclical imports of a record from Pure, then shifting back to AI.  So you can still create an ActivityInsightPublicationImport record, but only link it to the underlying publication record.  Do not update the actual record.

**Comment by ajkiessl** [comment]
#137
