### ISSUE TITLE
Automatically remove known non-duplicates with manual override

### ISSUE THREAD

**Issue by ajkiessl** [psu-stewardship/researcher-metadata#120]
If an admin is trying to group duplicates that have been marked as non-duplicates, have a dialog pop up that indicates these are non-duplicates and by continuing you will be overriding that.

**Comment by EricDurante** [comment]
@ajkiessl Just a heads-up if you were planning to start working on this issue at some point:

I might be making some significant changes to some of the same code and tests that you'd be touching in order to implement this. To avoid conflicts that might be difficult to resolve, we might want to do this one in series with what I'm currently working on if it can wait.

**Comment by ajkiessl** [comment]
@EricDurante Yeah no problem.  I hadn't planned on working on this just yet.

**Comment by ajkiessl** [comment]
Done in #158
