### ISSUE TITLE
Missing Resource Bug

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#135]
We had a user complain they received a "missing resource" when clicking on the link to upload OA article to ScholarSphere after the libraries email went out. Publication is: Caring for our colleagues: Wellness and support strategies for remote library teams

I believe we've had another person click on this but not mention an issue. Could it be possible that we need to update the link because of the latest ScholarSphere release?

**Comment by EricDurante** [comment]
Yes, I saw the error report for this. I haven't had a chance to look into it yet, but at a glance it looked like some sort of error caused by ActiveRecord not finding something that it was looking for.

For reference:  https://app.bugsnag.com/west-arete/psu-research-metadata/errors/60122b09dca1760018d107eb?event_id=60122b090069ad7d4b3a0000&i=sk&m=nw

**Comment by EricDurante** [comment]
@DanCoughlin

So I'm pretty sure what happened here is that the user double-clicked on the "Upload to Scholarsphere" button. The backend of RMD essentially did what it was supposed to do in this case, but the UI didn't handle that action well.

What happened was that the first click of the button sent a request to update the authorship record in RMD to indicate that the author had visited Scholarsphere to upload an open access copy of the publication. This succeeded, but before the request from the first click of the button could return a response to the user's browser (a redirect to Scholarsphere in this case), the second click sent a new request to do the same thing as the first request. Upon receiving the second request, RMD again looked for this publication among the set of publications that have an unknown open access status. Since the status was no longer unknown after the first click/request succeeded, RMD couldn't find the record, and the response that finally made it to the user's browser was a 404.

The solution to this is simple - disallow double-clicking that button by disabling it was javascript after it's clicked once (or something along those lines).

**Comment by EricDurante** [comment]
Oh, and yes, I see that we do _also_ need to update the Scholarsphere URL.

**Comment by EricDurante** [comment]
@DanCoughlin 

Both of these issues are now fixed in production.

As for the user who experienced the error, you can let them know that we identified and fixed the problem, and you can just direct them to go straight to Scholarsphere to deposit the work in question whenever they have a chance. Everything else should be in order.

**Comment by DanCoughlin** [comment]
Thank you!
