### ISSUE TITLE
Add User on Admin Not Working

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#139]
If you are trying to add an external publication waiver, and have to add a new user, you are unable to add a web access id for that user. The web access id field is required so you cannot add a user from this screen. Attaching screen shots to help see where I'm at. It's not urgent, I can add a user from the Users screen currently then come back to this screen.

![Screen Shot 2021-02-08 at 9 16 35 AM](https://user-images.githubusercontent.com/398837/107231607-80dc8280-69ee-11eb-98c0-cec83adbbf66.png)
![Screen Shot 2021-02-08 at 9 16 05 AM](https://user-images.githubusercontent.com/398837/107231621-8508a000-69ee-11eb-8b99-4913c48586ef.png)

**Comment by EricDurante** [comment]
@DanCoughlin 

This is an unsatisfying answer, but the problem here actually seems to be a small bug in the admin engine/framework that we're using. Often this framework adds all sorts of functionality to the UI by default with just a few declarative lines of code, so I actually wasn't even really aware that this inline form for creating user records had been added to the UI here (and that it didn't work properly). The apparent bug in the framework configuration means that I could make a change that would allow a user to be created with a WebAccess ID in this context, but it would mean also allowing the WebAccess ID of existing users to be edited (which I was really hoping to avoid since there hasn't been a need for it thus far).

So here are some options for addressing this:
1. Allow the WebAccess ID to be filled in here and edited elsewhere (easy, but discouraged)
2. Allow the WebAccess ID to be filled in here and try to apply some additional logic to prevent it from being edited where unnecessary (probably a little harder, but ideal)
3. Simply remove the button to create a new user here so that at least there isn't a broken feature on the page (easy, but disappointing)

**Comment by DanCoughlin** [comment]
@EricDurante either #3 or just leave as is. It's definitely not a priority, but good to have logged?

**Comment by EricDurante** [comment]
Ok, I did #3 so as to at least save some frustration in the future hopefully.

I made a note of the problem in this commit message too:  https://github.com/psu-stewardship/researcher-metadata/commit/7ce5ebc92b037071d229b83e6dbf61e49694bb2c
