### ISSUE TITLE
External Waivers occasionally not linking

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#146]
When working through external waivers and trying to link them to existing publications, in some cases I'm not able to link the publication listed in the external waiver to the publication in RMD. 

https://metadata.libraries.psu.edu/admin/external_publication_waiver/7
https://metadata.libraries.psu.edu/admin/external_publication_waiver/8
https://metadata.libraries.psu.edu/admin/external_publication_waiver/9

Linking that waiver produces an error that the link already exists but the ability to link the publication to that waiver is still there.

**Comment by EricDurante** [comment]
@DanCoughlin I'm trying to understand the workflow that led to this problem. Looking at the first example, it looks like you already created a waiver that you linked to this user's authorship:  https://metadata.libraries.psu.edu/admin/internal_publication_waiver/51. That's the reason for the error that you're seeing - an authorship should only be associated with one waiver, so the one that you already created prevents you from linking the external waiver. What was it that prompted you to create https://metadata.libraries.psu.edu/admin/internal_publication_waiver/51?

I presume that the proper resolution to this is for us to delete the waiver that you created and then link the external one that the author submitted, do you agree? Then maybe we need to give admins the ability to delete waivers (now that they can create them) and provide a little more visibility into how these records are connected?

**Comment by DanCoughlin** [comment]
@EricDurante  Ohhh, ok. Dang that was a good catch! The bigger issue is just making sure the publication has a waiver so the author wont be bothered to submit an OA copy if they've already submitted a waiver. Whether it's internal or external isn't as important AFAIK.

**Comment by EricDurante** [comment]
@DanCoughlin Gotcha. Still, at some point I think that we should make sure that this workflow is streamlined so that we don't end up with a bunch of "clutter" eventually.

In terms of satisfying the conditions for not sending the OA email, the type of waiver does matter. If _only_ an external waiver has been submitted for a publication that's actually in RMD, then an email will still be sent for that publication because we haven't made the connection between the waiver and the publication record yet. That's why it'll be important to stay on top of looking for matches and linking the external waivers. Creating the internal waivers manually, as you did in these cases, also satisfies the condition because that's part of what happens when you "link" an external waiver, but it's not the ideal workflow.

**Comment by DanCoughlin** [comment]
@EricDurante right, makes sense. Only linked waivers wont send emails.
