### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by awead** [psu-stewardship/researcher-metadata#201]
We're currently on Rails 5. 6.1 is the latest, with 7 just around the corner.

## WDLL

* upgrade to Rails 6.0.x or 6.1, whichever is possible with the least amount of hassle

## Dependencies
- [x] #255
- [x] #264
- [x] #287

**Comment by EricDurante** [comment]
@awead @DanCoughlin @cswalina 

Thanks, Adam, for making note of various things that need to be improved/upgraded. It's helpful to have fresh eyes on those things. This work is super important, and we want to stay on top of it, but in case you weren't aware - West Arete actually has a totally separate service contract for RMD that covers actually doing this type of work. So I wouldn't think that we'd want to queue these items up for development during the next couple of months unless they're absolutely critical or totally blocking something else that we're trying to accomplish.

In particular, we've already looked at the upgrade to rails 6.x because we had been planning to work on it a couple of months ago. It turned out to require quite a bit more work than expected (more than we had the capacity to do at the time), and there are still a few unanswered questions about how we're going to proceed with it. I'd be happy to share the info that we gathered or add it to this issue - whatever makes the most sense.

Anyway, I think it does make sense for the Libraries team to also become involved in this "service" work going forward, but I think we still have to figure out how that's going to work operationally compared to what we've been doing thus far.

**Comment by awead** [comment]
Thanks for the info.  If it's part of a separate contract, than it's probably not a wise use of resources to address it here. However, given that we're going to have a lot of devs for the next 8 weeks, we could consider it if we're looking for something to do.

Anyway, it's not my call, and there aren't any vulnerabilities currently.
