### ISSUE TITLE
De-duplicate Publications

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#22]
Conversation on basecamp - https://basecamp.com/1759334/projects/15421427/messages/88508508#comment_732991916 and https://basecamp.com/1759334/projects/15421427/messages/89238237#comment_741254712

We are working around getting publications deduplicated before turning on DM pulling from publications.

**Comment by DanCoughlin** [comment]
We need to figure out the best mechanism for getting the duplicates out of the system.
Selection is 1 based on talk with Brandy and Ana on 1/15
1. Auto-merge all existing duplicates
Then create a looser match on duplicates to get all the DM duplicates (there would also be false positives, likely) potentially missed duplicates but likely getting most of the duplicates by matching on title. Then any false positive (marked duplicate but it isn't really a duplicate) would need to be reconciled. We could handle this potentially on a case-by-case basis. As a faculty member says "where is my publication?" we go into the admin UI and mark the publication to no longer be a duplicate. This gets us to opening up the DM publications more quickly.

1b. We don't need to auto merge our existing duplicates, we could just add to those duplicates. The issue here is that our existing duplicates, we currently feel very strongly that they are duplicates, so now we are adding potential false positives to our duplicate data and it may ultimately make our duplicate data a bit fuzzy. 

2- The second option is more manual labor, where people go through every user in the database and mark which publications are duplicates. The problem here is we could potentially have to run this every time an import is run.

**Comment by DanCoughlin** [comment]
We need this stuff well documented in either FAQ or wiki of this. But I have another question on duplicates for @EricDurante How are duplicates factored in getting OA articles? If it's a duplicate in Digital Measures will we get an Open Access version twice?

**Comment by EricDurante** [comment]
No, we shouldn't. We currently search for open access info by DOI only, and this action doesn't create any new database records - it only adds open access info to existing publication records. 

If two publications in our database had the same DOI, then yes, we'd end up finding and saving the same open access info for each record. In that situation, the two publications are obviously duplicates, and now they'd also contain duplicate open access info, but the number of duplicate records remains the same. This is very unlikely to happen though, since Pure is our only really reliable source of publication DOIs. We haven't done any automatic deduplication of publications based on DOI to this point because in nearly every group of duplicate publications that we identify, at most only one in the group has a DOI listed.

**Comment by DanCoughlin** [comment]
Adding this https://3.basecamp.com/4206247/buckets/15288919/documents/2698994289 as additional discussion around this topic.

**Comment by EricDurante** [comment]
This issue is related to one that we added:  https://github.com/psu-stewardship/researcher-metadata/issues/42. I made additional comments there. We should probably have a little bit more in-person discussion about these and try to shake out a set of smaller, individually-actionable issues from these two.

**Comment by anaelizabethenriquez** [comment]
Duplication publication group 100670 was two articles with identical DOI values. We're not sure why these weren't automatically merged.

**Comment by ajkiessl** [comment]
Automatically merge publications as they come in on DOIs.

**Comment by EricDurante** [comment]
A little more background for this, and a few things to consider:

One reason why we haven't just been automatically merging duplicates based on DOI all along is that Pure used to be our only good source of publications with DOIs in their metadata, and there was very little duplication within Pure. That's no longer the case as there are now a lot of (correct) DOIs in Activity Insight, for example.

However, another reason why we hadn't been automatically merging duplicates is that we don't have an automatic process in place for combining the metadata on the publication itself. We _do_ have an automated process for merging things like Authorships and other RMD-generated records that are _associated_ with publications, but not for things like titles, journal names, page numbers, publication dates, etc. When merging happens manually, an admin has the opportunity to curate the metadata and build up the most complete and accurate set of metadata for the resulting publication record by looking at the metadata from each duplicate and combining/editing information field by field. 

We have done some automatic merging of duplicates in the past, but only for duplicates that meet certain criteria. Specifically, if we have a group of duplicates where one was imported from Pure and another was imported from Activity Insight, then we'll merge these automatically, but we haven't made any effort to merge or combine the publication metadata. Instead, we just take the metadata that came from Pure and ignore the metadata that came from Activity Insight altogether since, generally, Pure > Activity Insight in terms of metadata reliability/accuracy. So that process works well enough for those cases, but there are a lot of other duplicate merging circumstances where this isn't applicable - for example, any group of duplicates that does not include an import from Pure.

So DOIs, when we have them, solve the problem of publication disambiguation, but they don't solve the problem of optimally merging non-identical metadata from different sources. If we're going start automatically merging on matching DOIs, then we might also want to at least make some attempt at merging metadata instead of just arbitrarily picking one whole set to keep and discarding the other sets. At the very least, we could go field by field and look for fields that are blank in one record and present in another record and take the value that's present. If a value is present in more than one record and it's not the same in every record, then, depending on the field, we may be able to do some other simple validation to determine which value to keep. Otherwise, we may want to pick the value from what we think is the most reliable source, or pick a value randomly if the duplication is within the same source.

If we did automated publication metadata merging, I'm not sure if we'd want it to happen in cases where admins are still merging duplicates manually (i.e. where no DOI is present). We may or may not, but we should have a discussion with the admins who do the manual merging.

**Comment by EricDurante** [comment]
👆 I could be making too much of all of this, but what I'm thinking about here is aiming for the most complete and accurate set of metadata in RMD with the least amount of manual work possible.

**Comment by anaelizabethenriquez** [comment]
> We have done some automatic merging of duplicates in the past, but only for duplicates that meet certain criteria. Specifically, if we have a group of duplicates where one was imported from Pure and another was imported from Activity Insight, then we'll merge these automatically, but we haven't made any effort to merge or combine the publication metadata.

It would be great to do this again and/or set this up to happen automatically. Taking all the metadata fields from Pure seems pretty safe to me. I don't think it's currently happening. 4 of the 5 groups I mention in #374 would qualify for automatic merging on this basis.

> At the very least, we could go field by field and look for fields that are blank in one record and present in another record and take the value that's present.

That sounds good to me. For conflicts where none of the items comes from Pure, I think resolving the conflict depends on what the field is.

Tagging @nmg110 since this is about deduplication.

**Comment by EricDurante** [comment]
If we were to do everything that we possibly could do in terms of automatically merging publication metadata, I think that it would get pretty massively complicated. That's not to say that we can't or shouldn't do it all eventually, but we might be able to take an incremental approach to this where we start by only automatically merging the simplest cases and skipping over all others (leaving them to still be manually merged). The simplest cases, I suppose, would be where the only conflicts are between present and missing metadata values. Then we could gradually allow more and more things to be automatically merged as we add rules that permit more complex conflict resolution. Once we got to the point where the decisions are too tricky for a machine to make decisively, then we could leave whatever remains for humans to resolve.

**Comment by nmg110** [comment]
Alex and I found an issue today with auto-merging and pulling data from Pure. The example intoday's case of hbk3, she has 4 publication with the wrong Journal Title. We were able to figure out two things, one is Agronomy Journal is the new name for the Journal of Production Agriculture. Two, when looking at the Pure metadata we see 3 journal titles:
<titles>
    <title>Journal of Production Agriculture</title>
    <title>Agronomy Journal</title>
    <title>Journal of Production Agriculture</title>
  </titles>

Hello Profile Support,
 I just uploaded a publication into the database and noticed that the name of the Agronomy Journal is misrepresented for multiple publications in my Publication list.
It appears as Journal of Production Agriculture instead of Agronomy Journal for my recent 2021, 2020 and 2 2019 publications. If you click on the links, it is clear that the journal is the Agronomy Journal.
Would someone kindly correct this?

Thank you,
Heather Karsten, hdk3@psu.edu

Issues here is I cannot go in and change the Journal. If I add the correct title to Journal Title nothing happens, it still shows what was imported. I know this is only one user that we have identified, however how many more can there be?

**Comment by EricDurante** [comment]
@nmg110
This is a separate issue, but I think the problem that you're describing is happening because we have two different ways of storing journal information, but currently admins can only edit one of them. The one that you're able to edit is the lesser-preferred of the two, and so your change isn't showing up since there's a value in both places.

**Comment by ajkiessl** [comment]
@nmg110 Fine-tuning the auto-merging probably won't help us much with this issue.  I think we still want the journal records imported from Pure to take precedence.  In this specific case, the Activity Insight journal title is actually the correct one, though.  If we can fix this one in Pure then we should be good.  We may want to consider in the future linking publications imported from Activity Insight to Journal records imported from Pure if their titles match.

@EricDurante @anaelizabethenriquez I agree that we should slowly increment the complexity of this.  I can take a stab at merging records who share dois and whose only other conflict is between present and non-present data.  My only concern is that we don't improve much from our current situation if we are too strict.  I am seeing a lot of duplicates where the publication type is different, but they have the same doi and pretty much the same everything else.  Perhaps we can be more lenient with certain fields?

**Comment by anaelizabethenriquez** [comment]
> Perhaps we can be more lenient with certain fields?

Sounds right to me. Let me know if I can help with any details.

**Comment by ajkiessl** [comment]
related #374
