### ISSUE TITLE
Add cron task to run Unpaywall import

### ISSUE THREAD

**Issue by ajkiessl** [psu-stewardship/researcher-metadata#305]

**Comment by ajkiessl** [comment]
Run the full Unpaywall import in staging first.

**Comment by ajkiessl** [comment]
Run once a week.

**Comment by EricDurante** [comment]
I'll need to do this one.

**Comment by EricDurante** [comment]
This change is in the RMD chef repository, and it has been applied to the production server. The Unpaywall import is now scheduled to run every Tuesday beginning at 8 PM. This should be after the weekly OAB import has normally finished running, and since the data from those two sources overlaps quite a bit, this should help to keep RMD's OA metadata a little fresher. I've documented this change here:  https://github.com/psu-stewardship/researcher-metadata/pull/384
