### ISSUE TITLE
Users can claim publications to fulfill OA policies

### ISSUE THREAD

**Issue by ajkiessl** [psu-stewardship/researcher-metadata#316]
Students and staff (after creating an account) should be able to link themselves to preexisting publications.  

## WDDLL
* A tab or link in profile to find a publication
* That tab/link directs users to search feature to search existing publications by title or other users' names
* Datatable for searching with links to view some of the publication's metadata
* A button in the view to link the user to the viewed publication but it is not yet confirmed
* Adds authorship to user, set a field in authorship `waiting_for_confirmation` to true
* This publication should show up in the user's profile but should indicate it is waiting for confirmation
* Sends email to admin
* Admin must confirm the linking (in rails admin)

**Comment by EricDurante** [comment]
@anaelizabethenriquez @DanCoughlin 

When a user claims authorship of a publication, to what email address should the admin notification email be sent so that an admin can review/confirm the claim?

**Comment by anaelizabethenriquez** [comment]
@EricDurante @DanCoughlin I think we should set up a new address for this and forward it to the ticket queue (in LibAnswers) that Brandy and I manage, for now. Using a new address (rather than one of the addresses already going to that queue) will make it easier for us to spin off if necessary. I'm working with Brandy on setting up that new address.

**Comment by EricDurante** [comment]
Ok - thanks, @anaelizabethenriquez!

**Comment by anaelizabethenriquez** [comment]
@EricDurante You can use rmd-admin@psu.edu for these notification emails. For now that address forwards into our ticketing queue, but I can easily point it elsewhere if it becomes necessary.

**Comment by EricDurante** [comment]
Perfect!

**Comment by EricDurante** [comment]
Ah! Visibility wasn't the issue with the first publication that I picked in my demo this morning. It's working correctly with regard to visibility. It was the publication type that was the problem. I've made it so that only journal articles will appear in the search results now. That's a restriction that is somewhat arbitrary, but it supports the only use case (the open access workflow) that we currently have for claiming authorships without complicating anything else.

**Comment by anaelizabethenriquez** [comment]
Great! This will be something to remember if we do #178 someday.

**Comment by EricDurante** [comment]
Yep. It kind of makes me feel like we should change all of the language in the profile/management "Publications" tab to "journal article" instead of "publication" since it's really only journal articles in that list. All other types of publications are listed under "Other Works".

**Comment by anaelizabethenriquez** [comment]
We could even make it "scholarly article" to match the language of the OA policy, once we've got the logic on the OA workflow matching the OA policy as well.

**Comment by EricDurante** [comment]
If we begin to include more publication types in the OA workflows, I'm imagining that we'll still have separate listings of journal articles vs. all other types of publications just for the sake of profile organization (especially on the public side). The difference then would be that the listing of "Other Works" in the profile management UI would have the same open access information and actions as the list of journal articles, and the links in the emails would take you to the appropriate list for each publication.

I don't know if that separation is actually a big concern or not, but I'm thinking of the consumers of the public profile information and imagining that a lot of them would want to show lists of peoples' journal articles that don't have other kinds of publications mixed in. In that case, we also need to allow people to reorder those lists independently of each other in the profile management UI.
