### ISSUE TITLE
Profile page will not load

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#361]
I've tried several times last night and this morning to load the [profile page for mgn1](https://metadata.libraries.psu.edu/profiles/mgn1). From the admin side, this account looks normal to me.

I'm getting the following error:

> We're sorry, but something went wrong.
> 
> If you are the application owner check the logs for more information.
> 

I am able to load profile pages for other users.

**Comment by EricDurante** [comment]
That must be [this error](https://app.bugsnag.com/west-arete/researcher-metadata-database/errors/618946c28c77630008e70298?event_id=618948b000897b599a080000&i=sk&m=fq). Looks like there's more than one user with this problem.

**Comment by ajkiessl** [comment]
@EricDurante Should this be comparing the years for a CommitteeMembership?  Or some other attribute?

**Comment by EricDurante** [comment]
I see the problem here. In the production database, we have some `CommitteeMembership` records with a `role` of `"Thesis Advisor"`, but we don't have a ranking for that value [here](https://github.com/psu-stewardship/researcher-metadata/blob/cf9795b03e96e19fa89d3e00d5203167b7d0dc95/app/models/committee_membership.rb#L22). So we're trying to compare a number to nil in some cases.

This would be a very easy fix ...if we knew what the rank for that role should be compared to the others in the list. Incidentally, we _do_ have rankings for two roles that _don't_ appear in the production data currently: `"Special Member"` and `"Outside Member"`. Unfortunately this is one part of our code that we need to be careful to keep in sync with changes to the eTD app. It would be a good idea to at least have a fallback ranking (of `0` maybe) in RMD for any roles values that don't match a value in the list.

**Comment by EricDurante** [comment]
@ajkiessl We compare committee memberships by the significance of the member's role to determine which memberships to show first in their profile.

**Comment by ajkiessl** [comment]
@EricDurante I'll chat with Justin about this, and then work on a fix.  I think "Thesis Advisor" would be pretty high on the list.

**Comment by EricDurante** [comment]
Yeah, I assume that "Thesis Advisor" and "Dissertation Advisor" probably have equal significance.

**Comment by ajkiessl** [comment]
Also, since we are on the topic, I should mention that we recently (Spring 2021) added a lot of new roles for dissertations in eTD.  They are dynamic and are regularly imported from LionPATH.  I don't think they change often, but they can.  There are ~170 of them right now.  This is something we will have to address before we import eTDs again.

**Comment by ajkiessl** [comment]
Sounds good.  I'll add all of this.

**Comment by EricDurante** [comment]
Thanks, @ajkiessl!

**Comment by ajkiessl** [comment]
@anaelizabethenriquez This has been fixed and pushed to production.
