### ISSUE TITLE
Database snapshots

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#38]
In order to compare data and see how much we are progressing in Open Access, it's necessary to have data dumps of the database and archived somewhere. This way if our method for querying OA changes, we can back track our prior numbers.

**Comment by EricDurante** [comment]
Crudely, we already have this. We have automated nightly backups of the production site that include a full dump of the database. Going back in time, we eventually begin thinning out some of the older backups, but we keep monthly backups going back indefinitely.

We also have a task on our list to set up DSRD's internal backup system on these servers, which I assume would do something similar.

Do you think that satisfies this need? The backed-up data isn't super accessible, but it can be extracted if we need it. Otherwise, we could probably build in some kind of tracking/reporting mechanism that could give us this information on demand from the current production data.

**Comment by DanCoughlin** [comment]
Spoke at our meeting on 5/5/2020 about this and it does meet our need. When we ask for a data refresh then West Arete will provide a link to a database back up via dropbox or something like that for our records. The only concern at this point is making sure that the data dump is created prior to the data refresh running. In a worst case scenario, we could pull from backups to create a sql dump of the database.
