### ISSUE TITLE
Validation failing on user-submitted OA locations

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#387]
We've heard from a few users who've received the following error message when adding a URL to the user-submitted OA location field:

> Validation failed: URL is invalid or is unavailable at this time.

Here are two examples. They were provided by different users. Both users said they could access the URLs. But of course it's possible the sites weren't responding appropriately at the moment they tried the URLs in RMD. Maybe we just need to add a "please try again later" to the error text?

- https://www.sciencedirect.com/science/article/abs/pii/S0740547220304566?casa_token=qLxdGxshOYYAAAAA:6zt1y_mYwmuJjWQfUt7zP5RoAYQfJhsSeiw3y_w-PiN74pHdRSHFOghPLtJ1QVB6QY2dGIkyCA
- https://www.sciencedirect.com/science/article/pii/S0021929021004395

As I mentioned at stand-up, neither of these URLs is actually open access, but they do seem to be valid URLs.

**Comment by EricDurante** [comment]
So the first URL returns a 403 (forbidden) response when I use a programatic HTTP client, which is why it's failing the validation in RMD. However, when I request that URL in my browser, I never see a 403. Instead I get a 302 redirect (which would pass the RMD validation). I can't really imagine why this would be happening unless the web server that's hosting this article is doing some kind of user agent filtering.

**Comment by EricDurante** [comment]
I'd say that these URLs are unlikely to ever pass the current validations in RMD. Since we don't actually want these URLs, maybe we don't need to do anything about this. If we encounter a case where RMD is rejecting URLs that should work and that we _do_ want, then maybe we'll need to become more permissive on the validation at that point?

**Comment by anaelizabethenriquez** [comment]
While these two URLs are not OA, there are other URLs on that same site that are OA. Users should be able to save those values in this field. Here are a few examples:

- https://www.sciencedirect.com/science/article/am/pii/S0361923017302502
- https://www.sciencedirect.com/science/article/am/pii/S0016703720300338
- https://www.sciencedirect.com/science/article/abs/pii/S0278584617310412

Do these URLs fail the current validation?

**Comment by EricDurante** [comment]
They do.. in the same way as the others.

This is indeed happening because sciencedirect.com is denying access for certain user agents. So that's [easy](https://github.com/psu-stewardship/researcher-metadata/pull/393).

**Comment by anaelizabethenriquez** [comment]
Thanks, Eric!
