### ISSUE TITLE
Admin impersonating user1 cannot access Publications page of user2, for whom user1 is a proxy

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#400]
I'm not quite sure what's not working here. The problem might just be that I'm trying to test this from my admin account. Here's what happens:

- While acting as Brandy (bak25), I sent a request to Seth (sre53) to be Brandy's proxy.
- While acting as Seth, I confirmed that request.
- Still acting as Seth, I went to [Brandy's profile page](https://metadata-qa.libraries.psu.edu/profiles/bak25). My only option there is a button to "Unbecome this user." (This was unexpected. I expected to have to click "Become this user" on Brandy's profile.) There is no "manage profile" option. I also don't see a header on this page indicating I'm acting as Seth (or Brandy).
- If I try going directly to the URL for the [Manage Profile Publications page](https://metadata-qa.libraries.psu.edu/profile/publications/edit), it is the page for Seth, not Brandy. 
- I tried signing out and then signing back in. Then I went to Seth and Brandy's profile pages. On each page, there was a "Become this user" button, as I expected. On Seth's page, I clicked that button. 
- I entered the URL again for Brandy's profile page. The button there reads "Unbecome this user," just like I described above.
- I entered the URL for the Manage Profile Publications page, and it took me to Seth's page again.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Being an admin is partially the problem here.  You cannot proxy for someone while you are admin proxying for someone else.  You are viewing Brandy's public profile while proxying as Seth, so you must unbecome Seth before you become Brandy.  The wording "Unbecome this user" is a bit misleading too.  What happens when you click that button is you are signed out of whoever you are already proxying for.  So in this case, if you clicked that button you would unbecome Seth.  Then, the button to become Brandy would appear.  It may be more clear if the wording on that button indicated who you are still signed in as.  So it might say "Unbecome Seth Erickson".  Also, it would probably be helpful if the banner was still at the top of the screen that has the 'Stop being sre53' link.
