### ISSUE TITLE
Admin gets error "Deputy is not a assigned or available deputy" when depositing on behalf user

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#408]
I was just trying to make a ScholarSphere deposit using RMD on behalf of a user. I was able to "become" the user and navigate to the page for the publication, but when I tried to submit the deposit I got the error "Deputy is not a assigned or available deputy."

I don't think the deposit went through. I don't see it in the list of ScholarSphere work deposits or in ScholarSphere itself.

**Comment by EricDurante** [comment]
I took a quick look at this since I was in the neighborhood anyway, so maybe I can point somebody in the right direction. It looks like [this validation](https://github.com/psu-stewardship/researcher-metadata/blob/57f742ffe73e8a3f4e95f4fc346821fe8cd40e5b/app/models/concerns/deputy_user.rb#L21) needs to account for users who are masquerading by virtue of being an admin in addition to those who have been deputized. That's assuming that we want to store the admin's ID in the `deputy_user_id` fields whenever it's an admin who is acting on behalf of another user.

**Comment by awead** [comment]
@EricDurante I think that's right. Another option is to remove that validation. I'm not sure it's completely necessary, and furthermore, it's not a complete validation because we can't pin the exact user to their deputy easily. The UI, via `CurrentUserBuilder`, is handling the re-validation of a user/deputy relationship when any of the forms are loaded.

I wanted to put a "backend" validation in there to prevent any actions that weren't coming from the UI, like via a Rails admin form or console operation, from assigning a user that wasn't an actual deputy. Since in it seems to be having the opposite effect, I say we can take it out. That does mean an administrator would be able (technically) to assign _any_ user as the deputy for one of those particular actions, regardless of whatever their deputy/primary relationship was. Maybe that's a feature?

**Comment by ajkiessl** [comment]
Ah okay.  So it checks that the deputy has at least one deputy assignment.  Since admins won't have any, it throws an error.  That also explains why this was working for me in QA, since I hacked my admin user to have a deputy assignment via the rails console.

@awead I agree I think we can remove the validation.  I can do that today.  The way the validation works now, technically an admin could assign any user as a deputy for one of those actions so long as the deputy has at least one deputy assignment (if I'm understanding it correctly).  Since there isn't a way to do this through the rails admin, I think it's fine to pull the validation out entirely.  I'm not sure if allowing admins to add deputies to records would be a feature we want though.  It could help in cases where something isn't working properly and the deputy doesn't get set, but we'd expect that to be extremely rare or to not happen at all.

**Comment by awead** [comment]
The validation was really meant as a safe-guard for us, or anyone else who doesn't go through the UI, against updating or creating a deposit record using a deputy id that didn't correspond to an actual deputy. But, I the implementation is flawed and is now just getting in the way. The upshot is that an admin or anyone in the rails console, could add _any_ user as a deputy for a given deposit. 🤷 I don't think that's anything we have to be super concerned about. If anything, it might actually be a feature. It means we could assign any user as a deputy to a given deposit and not have to worry about the assignment process, but like you said that's going to be extremely rare or not happen at all.
