### ISSUE TITLE
Remove incorrect ScholarSphere OA URLs for Publication 423801

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#452]
[Publication 423801](https://metadata.libraries.psu.edu/admin/publication/423801) had an incorrect DOI. (I'm not sure why, but I have corrected it.) While the DOI was wrong, it imported a couple ScholarSphere URLs that are for that other DOI. Can you remove them? Here are the faulty OA locations:

https://metadata.libraries.psu.edu/admin/open_access_location/298477
https://metadata.libraries.psu.edu/admin/open_access_location/298521

I'm not sure if there's a way to prevent this from happening. If so, that might be worth writing up as a separate issue for later.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Was the other DOI: https://doi.org/10.1016/j.jalgebra.2021.11.015 ?  If so, it looks like this was a manual duplicate merge error.  The title for these two are very similar so they were probably matched as a duplicate group, and then merged by an admin.  I don't think this could have been merged by our automatic merges since one of those requires the two records to have the same DOI and the other requires one of the records to be from Activity Insight and the other from Pure.  This record has two Activity Insight imports.

We'll need to get the record back that was deleted from the merge.  I can do this by deleting the Activity Insight Publication Import attached to this publication that corresponds to the record with the other DOI.  This record will then be imported again from Activity Insight when the import runs again.

**Comment by ajkiessl** [comment]
I also removed the OA locations that were wrongly associated.  If you click the 'Delete' tab at the top of the screen when viewing an OA Location, you should be able to delete it as an admin.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl Yes, https://doi.org/10.1016/j.jalgebra.2021.11.015 was the other DOI. Removing that Activity Insight import so it can get refreshed sounds good.

And thanks for explaining how to delete incorrect OA locations -- I didn't realize I could do that in the admin interface.
