### ISSUE TITLE
Update unit names, e.g. "Worthington Scranton" to "Scranton"

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#454]
A faculty member at Penn State Scranton has pointed out that the campus changed its name (from "Worthington Scranton" to "Scranton") but this change is not reflected in RMD. I see that the organization names are still Worthington Scranton. I suspect there may other places that have "Worthington Scranton" as well -- perhaps related to #446. We should update all "Worthington Scranton" to "Scranton." 

It's possible there are other unit name changes not reflected in RMD, so generally refreshing this data (and making a plan for regular updates) would be good too.

I haven't found an official announcement about this, but [this Penn State News story](https://www.psu.edu/news/athletics/story/penn-state-brandywine-announces-first-ever-athletics-hall-fame-class/) refers to the name change, and I see "Penn State Scranton" on all official sources.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I've just heard from another person about this. (The name change was quite a while ago -- I think people are noticing because more folks are using RMD.) Do you know if there's any quick fix for this? Thanks!

**Comment by ajkiessl** [comment]
@anaelizabethenriquez We should probably get in touch with the folks who manage Pure to make this change.  We import all our Organization data from Pure, so if we were to make any changes locally they would be overwritten by the Pure import.  There are five organization records we get from Pure:

<img width="1366" alt="Screen Shot 2022-04-21 at 1 25 59 PM" src="https://user-images.githubusercontent.com/32677188/164516931-4e0544c0-2510-4473-b285-ccf06cb16757.png">

Our import runs on Saturday, so if they can make the change before the weekend we could get this fixed quickly.  Otherwise, I can manually run the import if it is urgent to get this fixed.  

A search in Pure shows two Scranton orgs that still have "Worthington" in the name: https://pennstate.pure.elsevier.com/en/organisations/?search=Scranton&pageSize=25&showAdvanced=false&allConcepts=true&inferConcepts=true&searchBy=PartOfNameOrTitle.  Once they get this changed in Pure and our import runs we can see if we need to make any manual changes.

**Comment by anaelizabethenriquez** [comment]
Thanks @ajkiessl ! I'll write to the Pure folks now.

**Comment by anaelizabethenriquez** [comment]
@ajkiessl I've heard back from the Pure team in Research. They will make the change "this week." I'm hoping that means we'll get the correct data with this Saturday's import. If not, we can wait for the next Saturday.

**Comment by ajkiessl** [comment]
@anaelizabethenriquez Ok that sounds good.  Thanks!

**Comment by anaelizabethenriquez** [comment]
Hi @ajkiessl - Looks the change is live in Pure and RMD has updated the org names for what are now called "Scranton Campus Library" and "Penn State Scranton." I see three orgs in RMD that haven't gotten a name change -- none of them has any members. I assume that means they won't be a problem? (Could users get added to them in the future?) Thanks!

474
Administration - Worthington Scranton
DEPT-CAM-WS-ADMIN
Department

364
University Libraries - Worthington Scranton
DEPT-WS-UL
Libraries

274
Faculty - Worthington Scranton
DEPT-CAM-WS-FACULTY
Department

**Comment by ajkiessl** [comment]
@anaelizabethenriquez They shouldn't be a problem.  Since these aren't in Pure anymore, they're probably not even touched by the Pure importer.  Users won't get added to them unless for some reason Pure adds them back in with the same Pure UUIDs (which shouldn't happen).

**Comment by anaelizabethenriquez** [comment]
Great. I think we're done!
