### ISSUE TITLE
Share Your Paper.org

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#73]
Embed Share Your Paper.org UI into our upload process for integration into ScholarSphere.

https://openaccessbutton.org/embedoa#
https://openaccessbutton.org/api

**Comment by EricDurante** [comment]
This may be able to replace our current "upload to Scholarsphere" workflow for potential open access publications. The idea is that we would allow faculty to upload publications directly from their metadata profile management interface to shareyourpaper.org instead of directing them to the Scholarsphere site to upload their materials. shareyourpaper.org does a good job of verifying that uploaded content is actually permitted to be open access and that it's not in violation of any licensing agreements. Once verified, the publication gets deposited in a temporary, public repository (Zenodo). Scholarsphere may then be able to integrate with Zenodo in such a way that it can retrieve the publication and metadata.

We'll still need to keep track of which publications in the metadata database have been uploaded to shareyourpaper.org successfully.

Some questions that come to mind:
- What happens when a user uploads a publication to shareyourpaper.org through the metadata database, but shareyourpaper.org later determines that the uploaded copy cannot be open access (and thus it's not deposited in Zenodo)? What does that workflow look like once it leaves our hands, and is there any way that we can be notified when things happen or change later?

**Comment by DanCoughlin** [comment]
Spoke with SYP and they mentioned: We'll be able to provide one for 'testing' that uploads to Zenodo's sandbox this month. That's ideal for making sure you're happy that it does what it says it does without risking archiving a bunch of publisher PDFs. We're still planning a version of SYP 'for production' without the Zenodo deposit.

I think the testing upload is a good first step for us.

**Comment by EricDurante** [comment]
Perfect! I was wondering how we would try this out. I'm glad they're making a sandbox available.

**Comment by DanCoughlin** [comment]
Ended up integrating the RMD UI with our own work.
