### ISSUE TITLE
Integrate articles from law schools

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#79]
We should look into the BePress OAI-PMH for both law schools to see if we can link in the existing articles for our law 
school publications. The law schools have a well curated repository of Penn State law articles so we believe we can harvest
that content from there.

There are 2 law school repos
1- Dickinson
For the IDEAS repository, that URL is:
https://ideas.dickinsonlaw.psu.edu/do/oai/  

Additional information about using OAI to harvest metadata from Digital Commons is available at:
https://www.bepress.com/reference_guide_dc/digital-commons-oai-harvesting/

Basically, Digital Commons exposes a default set of Dublin Core elements through the oai_dc format.  For the oai_dc format, the query using that base URL would look like this:
http://ideas.dickinsonlaw.psu.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc

To expose metadata that is not included by default but instead has been custom mapped to Dublin Core elements, the prefix dcs or dcq needs to be used instead of oai_dc. To use the dcs or dcq format, the queries would look like this:
http://ideas.dickinsonlaw.psu.edu/do/oai/?verb=ListRecords&metadataPrefix=dcs  
http://ideas.dickinsonlaw.psu.edu/do/oai/?verb=ListRecords&metadataPrefix=dcq

2- Penn State Law
OAI End Point https://elibrary.law.psu.edu/do/oai

I believe the info above for Dickinson is consistent for Penn State Law:
https://elibrary.law.psu.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc

**Comment by EricDurante** [comment]
This is data that we may not yet have at all since it most likely isn't present in Pure, and the law schools are not currently using Activity Insight. So we'll be importing largely or entirely new publication data from this source, but we may also not have the associated user metadata yet. We'll have to look at a sample of the data and determine whether it's complete enough by itself to meet our needs or whether we'll need to pull in some data from some other source also.

Once we have this data imported, it would be helpful if we were able to export it in such a way that it would be easy to import into Activity Insight, since the law schools may start using that tool soon.
