### ISSUE TITLE
Speed up duplicate checks

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#82]
When we import publication data, the check for duplicates is slow. We are going to look at ways to improve the speed of that if we are going to import data on a more regular basis to prevent any issues of speed.

**Comment by EricDurante** [comment]
One way that we may be able to accomplish this is by building a GIN or GiST index on the title column for publications.

https://www.postgresql.org/docs/current/pgtrgm.html#id-1.11.7.40.7

**Comment by EricDurante** [comment]
I tried a few permutations of my original idea for this, but none of them seemed to improve anything. However, I discovered something simpler that seems to have sped the queries up by a couple of orders of magnitude. This should be enough to allow the whole process to complete in less than a day instead of taking weeks.
