### ISSUE TITLE
Prepare Law School Citations for Digital Measures

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/researcher-metadata#83]
Once we are able to capture all the citations from law school repos into MDDB, we should look at how that data will most easily get into the Digital Measures so when we onboard the law school, we are able to import their data.

**Comment by DanCoughlin** [comment]
On export for authorship Id [Contributors], First name [Contributors 1], Middle name [Contributors 1], Last Name [Contributors 1] we will now get the penn state access account for the Id [Contributors] column and then explode the other lists of first, middle, and last names to have a column for each first, middle and last name.

**Comment by EricDurante** [comment]
Honestly, since the set of metadata that we get from the law school repos is pretty limited compared to what can be stored in Digital Measures or even the metadata database, and since we need to be able to select only the law school publications for import, the easiest thing to do for this special case of onboarding might be to write a little bit of code that takes in the law school metadata and dumps it directly to a CSV file that Digital Measures can understand. It could import the data to the metadata database at the same time, but then we wouldn't need to worry about customizing the already complex filtering and CSV exporting functionality of the metadata DB admin interface.
